Console.ForegroundColor = ConsoleColor.DarkMagenta;  
Console.WriteLine("Contando até dez:"); Thread.Sleep(1000);
Console.ResetColor();
Console.WriteLine("0 "); Thread.Sleep(500);
Console.WriteLine("1 "); Thread.Sleep(500);
Console.WriteLine("2 "); Thread.Sleep(500);
Console.WriteLine("3 "); Thread.Sleep(500);
Console.WriteLine("4 "); Thread.Sleep(500);
Console.WriteLine("5 "); Thread.Sleep(500);
Console.WriteLine("6 "); Thread.Sleep(500);
Console.WriteLine("7 "); Thread.Sleep(500);
Console.WriteLine("8 "); Thread.Sleep(500);
Console.WriteLine("9 "); Thread.Sleep(500);
Console.WriteLine("10 ");